### ISSUE TITLE
Wrong date for Boston, Hoosic, Tunnel & Western Railroad v...

### ISSUE THREAD

**Issue by mlissner** [freelawproject/opinionated#29]
Here's the link: https://www.courtlistener.com/opinion/5625986/boston-hoosic-tunnel-western-railroad-v-troy-boston-railroad/

It's from the Harvard corpus. It should be 1879, not 1819. 

A user reported this. I haven't changed our data. Figured either @quevon24 or @flooie would make more sense to take it on, so we could add it here as well. 

Thoughts? Is this a useful way to handle errors?

**Comment by mlissner** [comment]
Here's the link in Harvard: https://cite.case.law/how-pr/58/167/

Check the PDF to see the correct date.

**Comment by quevon24** [comment]
It seems that the data from case.law is also incorrect [https://api.case.law/v1/cases/4514248/](https://api.case.law/v1/cases/4514248/) The problem seems to come from the source, probably because a bad ocr. The easiest way to fix this is creating an opinionated fix by changing the date.

I think it's hard to handle this kind of errors automatically because we import the data into courtlistener using the data from the source. If the source data is wrong, ours will be wrong too. We can know if some data is incorrect when we run the harvard importer, using the logs, it probably won't be importer until we fix it.

But in this situation, I think the user feedback works very well because probably no one will find an error until someone else reviews the case, find something like an incorrect date, and reports it.

I'll try to think of something else that can help us.

**Comment by mlissner** [comment]
Yeah, that sounds right. Bill, should Kevin take this on to put a fix in CL and in Opinionated?

**Comment by flooie** [comment]
Yes I think so.  We have an outstanding opinionated PR we should be able to add this too.

**Comment by quevon24** [comment]
This has already been fixed in this PR: https://github.com/freelawproject/opinionated/pull/26

I'm closing the issue.
